import { Geist, Geist_Mono, Inter, Manrope } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;
// import { ThemeProvider } from "./components/themeprovider";
import ScrollToTopButton from "@/ScrollToTop";
const inter = Inter({
  variable: "--font-in",
  display:"swap",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-mr",
  subsets: ["latin"],
  display:"swap"
});

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${manrope.variable} antialiased`}
      >
        <Header></Header>
        {children}
        {/* <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider> */}
          <ScrollToTopButton></ScrollToTopButton>
        <Footer></Footer>
      </body>
    </html>
  );
}
